#ifndef _RES_RESOURCES_H_
#define _RES_RESOURCES_H_

extern const Image titlescreen;
extern const Image intro;
extern const Image intro2;
extern const Image naxat;
extern const Image indiano;
extern const SpriteDefinition level_stage;
extern const SpriteDefinition level_numbers;
extern const TileSet characters;
extern const SpriteDefinition hud_slasher;
extern const SpriteDefinition slasher;
extern const SpriteDefinition slasher_big_0;
extern const SpriteDefinition slasher_big_2;
extern const SpriteDefinition slasher_big_3;
extern const SpriteDefinition slasher_big_4;
extern const SpriteDefinition slasher_big_5;
extern const SpriteDefinition slasher_weapon_0001;
extern const SpriteDefinition star_warp;
extern const SpriteDefinition enemy_0001;
extern const SpriteDefinition enemy_0002;
extern const SpriteDefinition enemy_0003;
extern const SpriteDefinition enemy_0004;
extern const SpriteDefinition enemy_0005;
extern const SpriteDefinition enemy_0006;
extern const SpriteDefinition enemy_0007;
extern const SpriteDefinition enemy_0008_001;
extern const SpriteDefinition enemy_0008_002;
extern const SpriteDefinition enemy_0008_003;
extern const SpriteDefinition enemy_0008_004;
extern const SpriteDefinition enemy_0008_005;
extern const SpriteDefinition enemy_0008_006;
extern const SpriteDefinition enemy_0008_007;
extern const SpriteDefinition enemy_0008_008;
extern const SpriteDefinition enemy_0008_009;
extern const SpriteDefinition enemy_0008_010;
extern const SpriteDefinition enemy_0008_011;
extern const SpriteDefinition enemy_0008_012;
extern const SpriteDefinition enemy_0008_013;
extern const SpriteDefinition enemy_0008_014;
extern const SpriteDefinition enemy_0008_015;
extern const SpriteDefinition enemy_0008_016;
extern const SpriteDefinition enemy_0008_017;
extern const SpriteDefinition enemy_0008_018;
extern const SpriteDefinition enemy_0008_019;
extern const SpriteDefinition enemy_0008_020;
extern const SpriteDefinition enemy_0008_01;
extern const SpriteDefinition enemy_0008_02;
extern const SpriteDefinition enemy_0009;
extern const SpriteDefinition enemy_0010;
extern const SpriteDefinition enemy_0010_intro;
extern const SpriteDefinition enemy_explosion;
extern const SpriteDefinition enemy_explosion_big;
extern const SpriteDefinition enemy_bullet_001;
extern const SpriteDefinition stage1_explosions;
extern const Image custom_font;

#endif // _RES_RESOURCES_H_
