#ifndef LANG_EN_H
#define LANG_EN_H

#define LANG_EN_TXT_CURRENT_LANG "ENGLISH"

#define LANG_EN_TXT_START "GAME START"
#define LANG_EN_TXT_OPTIONS "OPTIONS"
#define LANG_EN_TXT_EXIT "EXIT"

#define LANG_EN_TXT_LANGUAGE "LANGUAGE"
#define LANG_EN_TXT_DIFFICULTY "DIFFICULTY"
#define LANG_EN_TXT_CREDITS "CREDITS"
#define LANG_EN_TXT_BACK "BACK"

#define LANG_EN_TXT_ON "ON"
#define LANG_EN_TXT_OFF "OFF"

#endif
