#ifndef LANG_PT_H
#define LANG_PT_H

#define LANG_PT_TXT_CURRENT_LANG "PORTUGUES"

#define LANG_PT_TXT_START "INICIAR"
#define LANG_PT_TXT_OPTIONS "OPCOES"
#define LANG_PT_TXT_EXIT "SAIR"

#define LANG_PT_TXT_LANGUAGE "IDIOMA"
#define LANG_PT_TXT_DIFFICULTY "DIFICULDADE"
#define LANG_PT_TXT_CREDITS "CREDITOS"
#define LANG_PT_TXT_BACK "VOLTAR"

#define LANG_PT_TXT_ON "LIGADO"
#define LANG_PT_TXT_OFF "DESLIGADO"

#endif
