#ifndef LANG_ES_H
#define LANG_ES_H

#define LANG_ES_TXT_CURRENT_LANG "ESPANHOL"

#define LANG_ES_TXT_START "COMENZAR"
#define LANG_ES_TXT_OPTIONS "OPCIONES"
#define LANG_ES_TXT_EXIT "SALIR"

#define LANG_ES_TXT_LANGUAGE "LINGUA"
#define LANG_ES_TXT_DIFFICULTY "DIFICULDAD"
#define LANG_ES_TXT_CREDITS "CREDITOS"
#define LANG_ES_TXT_BACK "VOLVER"

#define LANG_ES_TXT_ON "ENCENDIDO"
#define LANG_ES_TXT_OFF "NO ENCENDIDO"

#define LANG_ES_TXT_PAUSED "PAUSADO"

#endif
